<?php

namespace Database\Seeders;

use App\Support\InternetSimSheetImporter;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

/**
 * The site internet SIM lines as at August 2026, taken from the month's
 * sheet.
 *
 * Safe to run more than once. It feeds the same importer the upload button
 * uses, so a line is matched on SIM number, account site and SIM S/N
 * together and updated rather than duplicated. The same SIM appearing on
 * several rows is expected: copies of a line, at different sites or the
 * same one.
 *
 * Rows are recorded as at 1 August 2026, so they appear on the August
 * report and carry forward to every month after it.
 *
 *     php artisan db:seed --class=InternetSimAugust2026Seeder
 */
class InternetSimAugust2026Seeder extends Seeder
{
    public function run(): void
    {
        $importer = (new InternetSimSheetImporter)
            ->importRows($this->rows(), Carbon::create(2026, 8, 1));

        $this->command?->info($importer->summary());
        foreach ($importer->warnings as $warning) {
            $this->command?->warn($warning);
        }
    }

    /** One entry per line on the August sheet, in sheet order. */
    private function rows(): array
    {
        return [
            1 => [
                'sim_number' => '548888223',
                'sim_provider' => 'ETISALAT',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'ENG. FADI',
                'line_active' => true,
                'sim_serial' => '8997112212769842898',
                'contract_no' => '',
                'router_serial' => '22234B1005586',
                'remark' => 'ORION',
            ],
            2 => [
                'sim_number' => '548888223',
                'sim_provider' => 'ETISALAT',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'RAK273-60WAREHOUSES',
                'line_active' => true,
                'sim_serial' => '8997112212773701739',
                'contract_no' => '',
                'router_serial' => '2211H3003824',
                'remark' => 'CAMERA SYS',
            ],
            3 => [
                'sim_number' => '548888223',
                'sim_provider' => 'ETISALAT',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'Eng. Fayez Flat',
                'line_active' => true,
                'sim_serial' => '8997112212773701705',
                'contract_no' => '',
                'router_serial' => '',
                'remark' => 'ORION',
            ],
            4 => [
                'sim_number' => '548888551',
                'sim_provider' => 'ETISALAT',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'MAIN OFFICE',
                'line_active' => false,
                'sim_serial' => '8997112212768122209',
                'contract_no' => '',
                'router_serial' => '',
                'remark' => 'WAS 246',
            ],
            5 => [
                'sim_number' => '548888551',
                'sim_provider' => 'ETISALAT',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'ENGR MANSOOR',
                'line_active' => true,
                'sim_serial' => '8997112212773701802',
                'contract_no' => '',
                'router_serial' => '',
                'remark' => 'ORION',
            ],
            6 => [
                'sim_number' => '548888551',
                'sim_provider' => 'ETISALAT',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'RAK261 Warehouses 50,000 m',
                'line_active' => true,
                'sim_serial' => '8997112212768122206',
                'contract_no' => '',
                'router_serial' => '',
                'remark' => 'CAMERA SYS',
            ],
            7 => [
                'sim_number' => '548888551',
                'sim_provider' => 'ETISALAT',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'RAK273-60WAREHOUSES',
                'line_active' => true,
                'sim_serial' => '899712212768122186',
                'contract_no' => '36732602/68090131',
                'router_serial' => 'JX1ANK3012375',
                'remark' => 'ORION',
            ],
            8 => [
                'sim_number' => '564889948',
                'sim_provider' => 'ETISALAT',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'ATEIA HOME',
                'line_active' => true,
                'sim_serial' => '8997112212780191222',
                'contract_no' => '',
                'router_serial' => '',
                'remark' => 'ORION',
            ],
            9 => [
                'sim_number' => '564889948',
                'sim_provider' => 'ETISALAT',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'RAK262 - Boscalis',
                'line_active' => true,
                'sim_serial' => '8997112212780191220',
                'contract_no' => '',
                'router_serial' => '',
                'remark' => 'CCTV NVR1',
            ],
            10 => [
                'sim_number' => '564889948',
                'sim_provider' => 'ETISALAT',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'Lotus Factory',
                'line_active' => true,
                'sim_serial' => '8997112212780191221',
                'contract_no' => '',
                'router_serial' => '',
                'remark' => 'CCTV NVR2',
            ],
            11 => [
                'sim_number' => '564889948',
                'sim_provider' => 'ETISALAT',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'RAK264 HULAILA  SUNREEF',
                'line_active' => false,
                'sim_serial' => '8997112212769842898',
                'contract_no' => '',
                'router_serial' => '',
                'remark' => 'STOCK',
            ],
            12 => [
                'sim_number' => '527992130',
                'sim_provider' => 'DU',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'RAK261 Warehouses 50,000 m',
                'line_active' => true,
                'sim_serial' => '8997103524022314250',
                'contract_no' => '',
                'router_serial' => '',
                'remark' => 'CAMERA SYS',
            ],
            13 => [
                'sim_number' => '527992130',
                'sim_provider' => 'DU',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'ESTIMATION Dep',
                'line_active' => true,
                'sim_serial' => '8997103524022314235',
                'contract_no' => '52125681/18806634',
                'router_serial' => 'U40D125023848',
                'remark' => 'ORION',
            ],
            14 => [
                'sim_number' => '527992130',
                'sim_provider' => 'DU',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'RAK264 - Sunreef',
                'line_active' => true,
                'sim_serial' => '8997103123067416037',
                'contract_no' => '77877667/94955002',
                'router_serial' => 'JX1AAK5009329',
                'remark' => 'CAMERA SYS',
            ],
            15 => [
                'sim_number' => '527992130',
                'sim_provider' => 'DU',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'eng. fadi',
                'line_active' => true,
                'sim_serial' => '8997112212758998257',
                'contract_no' => '',
                'router_serial' => '220A4P5000382',
                'remark' => 'ORION',
            ],
            16 => [
                'sim_number' => '555521940',
                'sim_provider' => 'DU',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'IT DEP.',
                'line_active' => true,
                'sim_serial' => '8997103123067416169',
                'contract_no' => '16680990/57835842',
                'router_serial' => '',
                'remark' => 'client',
            ],
            17 => [
                'sim_number' => '555521940',
                'sim_provider' => 'DU',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'DXB005 Mudon School',
                'line_active' => true,
                'sim_serial' => '8997103124146617520',
                'contract_no' => '54312513/80456419',
                'router_serial' => '',
                'remark' => 'ORION',
            ],
            18 => [
                'sim_number' => '555521940',
                'sim_provider' => 'DU',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'RAK262 - Boscalis',
                'line_active' => true,
                'sim_serial' => '8997103123067416011',
                'contract_no' => '61047323/93028361',
                'router_serial' => '220C2W4000066',
                'remark' => 'client',
            ],
            19 => [
                'sim_number' => '555521940',
                'sim_provider' => 'DU',
                'account_name' => 'Eng. Saqer',
                'account_site' => 'NEED REPLACMENT',
                'line_active' => true,
                'sim_serial' => '8997103123067416029',
                'contract_no' => '77574183/65335662',
                'router_serial' => '220C2W4000067',
                'remark' => 'ORION',
            ],
            20 => [
                'sim_number' => '523607250',
                'sim_provider' => 'DU',
                'account_name' => 'Orion',
                'account_site' => 'RAK257  XPRO',
                'line_active' => true,
                'sim_serial' => '8997103124306162853',
                'contract_no' => '',
                'router_serial' => '861192060577791',
                'remark' => 'ORION',
            ],
            21 => [
                'sim_number' => '508173142',
                'sim_provider' => 'ETISALAT',
                'account_name' => 'Mwafaq',
                'account_site' => 'RAK264 - Sunreef',
                'line_active' => true,
                'sim_serial' => '89971031230694550909',
                'contract_no' => '',
                'router_serial' => '61988010166561',
                'remark' => 'ORION',
            ],
            22 => [
                'sim_number' => '527246732',
                'sim_provider' => 'DU',
                'account_name' => 'Ateia El-Nakla',
                'account_site' => 'Orion Farm',
                'line_active' => true,
                'sim_serial' => '8997103123067416037',
                'contract_no' => '',
                'router_serial' => '',
                'remark' => 'ORION',
            ],
            23 => [
                'sim_number' => '525514224',
                'sim_provider' => 'DU',
                'account_name' => 'Orion',
                'account_site' => 'RAK266 LABOR ACCMODATION',
                'line_active' => true,
                'sim_serial' => '8997103124134889693',
                'contract_no' => '',
                'router_serial' => 'X28864542061676520',
                'remark' => 'ORION',
            ],
            24 => [
                'sim_number' => '581806471',
                'sim_provider' => 'DU',
                'account_name' => 'Orion',
                'account_site' => 'HEAD OFFICE',
                'line_active' => true,
                'sim_serial' => '8997103524076898513',
                'contract_no' => '',
                'router_serial' => '864542061648305',
                'remark' => 'ORION',
            ],
            25 => [
                'sim_number' => '525220120',
                'sim_provider' => 'DU',
                'account_name' => 'Orion',
                'account_site' => 'RAK261 - Warehouses 50,000 m',
                'line_active' => true,
                'sim_serial' => '899710312419835092',
                'contract_no' => '28023718/93728060',
                'router_serial' => 'X288864542061617342',
                'remark' => 'ORION',
            ],
            26 => [
                'sim_number' => '581806914',
                'sim_provider' => 'DU',
                'account_name' => 'Orion',
                'account_site' => 'ENGR FADI',
                'line_active' => true,
                'sim_serial' => '8997103524076898570',
                'contract_no' => 'CONTR0144297002',
                'router_serial' => 'X28864542601646531',
                'remark' => 'ORION',
            ],
            27 => [
                'sim_number' => '589568489',
                'sim_provider' => 'DU',
                'account_name' => 'Orion',
                'account_site' => 'MAIN OFFICE',
                'line_active' => false,
                'sim_serial' => '889713012472001383',
                'contract_no' => '',
                'router_serial' => 'X28864542061639759',
                'remark' => 'WAS AIN FARM',
            ],
            28 => [
                'sim_number' => '581267451',
                'sim_provider' => 'DU',
                'account_name' => 'Orion',
                'account_site' => 'RAK266 LABOR ACCMODATION',
                'line_active' => true,
                'sim_serial' => '',
                'contract_no' => '',
                'router_serial' => '',
                'remark' => 'Clint',
            ],
            29 => [
                'sim_number' => '581267452',
                'sim_provider' => 'DU',
                'account_name' => 'Orion',
                'account_site' => 'RAK266 LABOR ACCMODATION',
                'line_active' => true,
                'sim_serial' => '',
                'contract_no' => '',
                'router_serial' => '',
                'remark' => 'Consultant',
            ],
            30 => [
                'sim_number' => '581267453',
                'sim_provider' => 'DU',
                'account_name' => 'Orion',
                'account_site' => 'RAK266 LABOR ACCMODATION',
                'line_active' => true,
                'sim_serial' => '8997103124240270325',
                'contract_no' => 'CONTR0165673060',
                'router_serial' => '',
                'remark' => 'ORION',
            ],
            31 => [
                'sim_number' => '581267433',
                'sim_provider' => 'DU',
                'account_name' => 'Orion',
                'account_site' => 'RAK267 STAFF ACCMODATION',
                'line_active' => true,
                'sim_serial' => '8997103124240270317',
                'contract_no' => 'CONTR0165673212',
                'router_serial' => '',
                'remark' => 'ORION',
            ],
            32 => [
                'sim_number' => '589528398',
                'sim_provider' => 'DU',
                'account_name' => 'Orion',
                'account_site' => 'DXB005 Mudren School',
                'line_active' => true,
                'sim_serial' => '899710312417199832',
                'contract_no' => '',
                'router_serial' => 'X28864542061639759',
                'remark' => 'ORION',
            ],
            33 => [
                'sim_number' => '581827607',
                'sim_provider' => 'DU',
                'account_name' => 'Orion',
                'account_site' => 'DXB005 Mudren School',
                'line_active' => true,
                'sim_serial' => '8997103124191828493',
                'contract_no' => '',
                'router_serial' => 'X28864542061645913',
                'remark' => 'MEP-CONSULTANT',
            ],
            34 => [
                'sim_number' => '581270784',
                'sim_provider' => 'DU',
                'account_name' => 'Orion',
                'account_site' => 'SH0011 -STP KALBA',
                'line_active' => true,
                'sim_serial' => '8997103124240336258',
                'contract_no' => '',
                'router_serial' => 'X26P550241062242424',
                'remark' => 'ORION',
            ],
            35 => [
                'sim_number' => '525172187',
                'sim_provider' => 'DU',
                'account_name' => 'Orion',
                'account_site' => 'ENGER FAYEZ-DUBAI APPARTMENT',
                'line_active' => true,
                'sim_serial' => '899710312436166433',
                'contract_no' => '',
                'router_serial' => 'X28P860241062237846',
                'remark' => 'ORION',
            ],
            36 => [
                'sim_number' => '559491726',
                'sim_provider' => 'DU',
                'account_name' => 'Orion',
                'account_site' => 'RAK273 60K WAREHOUSES',
                'line_active' => true,
                'sim_serial' => '8997103124240122112',
                'contract_no' => 'CONTR0174871449',
                'router_serial' => 'X28p860241062483382',
                'remark' => 'ORION',
            ],
            37 => [
                'sim_number' => '559491873',
                'sim_provider' => 'DU',
                'account_name' => 'Orion',
                'account_site' => 'Lotus Factory',
                'line_active' => true,
                'sim_serial' => '8997103124240122120',
                'contract_no' => '',
                'router_serial' => 'X28P860241062484190',
                'remark' => 'ORION',
            ],
            38 => [
                'sim_number' => '',
                'sim_provider' => 'DU',
                'account_name' => 'Orion',
                'account_site' => 'RAK273 60K WAREHOUSES',
                'line_active' => true,
                'sim_serial' => '8997103124240122112',
                'contract_no' => 'CONTR0174871449',
                'router_serial' => 'X28p860241062483382',
                'remark' => 'ORION',
            ],
        ];
    }
}
