<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PositionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [ 'id' => 1 , 'name' => 'IT Manager', 'department_id' => 1],
            [ 'id' => 2 , 'name' => 'IT Administrator', 'department_id' => 1],
            [ 'id' => 3 , 'name' => 'Junior Accountant', 'department_id' => 2],
            [ 'id' => 4 , 'name' => 'Senior Accountant', 'department_id' => 2],
            [ 'id' => 5 , 'name' => 'Accountant Assistant', 'department_id' => 2],
            [ 'id' => 6 , 'name' => 'Draftsman', 'department_id' => 3],
            [ 'id' => 7 , 'name' => 'Architect Manager', 'department_id' => 3],
            [ 'id' => 8 , 'name' => 'Architectural Engineer', 'department_id' => 3],
            [ 'id' => 9 , 'name' => 'Construction Manager', 'department_id' => 4],
            [ 'id' => 10 , 'name' => 'Civil Engineer', 'department_id' => 4],
            [ 'id' => 11 , 'name' => 'QA/QC Engineer', 'department_id' => 4],
            [ 'id' => 112 , 'name' => 'QS Engineer', 'department_id' => 4],
            [ 'id' => 12 , 'name' => 'Project Manager', 'department_id' => 4],
            [ 'id' => 13 , 'name' => 'Structural Engineer', 'department_id' => 4],
            [ 'id' => 14 , 'name' => 'Civil Foreman', 'department_id' => 4],
            [ 'id' => 15 , 'name' => 'Charge Hand', 'department_id' => 4],
            [ 'id' => 16 , 'name' => 'Cost Control Engineer', 'department_id' => 5],
            [ 'id' => 17 , 'name' => 'Document Controller', 'department_id' => 5],
            [ 'id' => 18 , 'name' => 'Civil Engineer', 'department_id' => 5],
            [ 'id' => 19 , 'name' => 'Procurement Officer', 'department_id' => 5],
            [ 'id' => 20 , 'name' => 'Planning Engineer', 'department_id' => 5],
            [ 'id' => 21 , 'name' => 'Document Controller', 'department_id' => 6],
            [ 'id' => 22 , 'name' => 'Estimation Manager', 'department_id' => 7],
            [ 'id' => 23 , 'name' => 'Estimation Engineer', 'department_id' => 7],
            [ 'id' => 24 , 'name' => 'Logistics Manager', 'department_id' => 8],
            [ 'id' => 25 , 'name' => 'HR & Admin Assistant', 'department_id' => 8],
            [ 'id' => 26 , 'name' => 'PRO', 'department_id' => 8],
            [ 'id' => 27 , 'name' => 'HR Executive', 'department_id' => 8],
            [ 'id' => 28 , 'name' => 'AC HELPER', 'department_id' => 9],
            [ 'id' => 29 , 'name' => 'AC Technician', 'department_id' => 9],
            [ 'id' => 30 , 'name' => 'Asst Electrician', 'department_id' => 9],
            [ 'id' => 31 , 'name' => 'AC Plumber', 'department_id' => 9],
            [ 'id' => 32 , 'name' => 'AC SURVEYOR', 'department_id' => 9],
            [ 'id' => 113 , 'name' => 'ASST SURVEYOR', 'department_id' => 9],
            [ 'id' => 33 , 'name' => 'BOBCAT OPERATOR', 'department_id' => 9],
            [ 'id' => 34 , 'name' => 'Boom Loader Operator', 'department_id' => 9],
            [ 'id' => 35 , 'name' => 'BUS DRIVER', 'department_id' => 9],
            [ 'id' => 36 , 'name' => 'Camp Boss', 'department_id' => 9],
            [ 'id' => 37 , 'name' => 'Carpenter', 'department_id' => 9],
            [ 'id' => 38 , 'name' => 'Charge Hand', 'department_id' => 9],
            [ 'id' => 39 , 'name' => 'Charge hand-MEP', 'department_id' => 9],
            [ 'id' => 40 , 'name' => 'Document Controller', 'department_id' => 9],
            [ 'id' => 41 , 'name' => 'Driver', 'department_id' => 9],
            [ 'id' => 42 , 'name' => 'Electrician', 'department_id' => 9],
            [ 'id' => 43 , 'name' => 'Erector', 'department_id' => 9],
            [ 'id' => 44 , 'name' => 'FABRICATOR', 'department_id' => 9],
            [ 'id' => 45 , 'name' => 'Foreman', 'department_id' => 9],
            [ 'id' => 46 , 'name' => 'Helper', 'department_id' => 9],
            [ 'id' => 47 , 'name' => 'JCB DRIVER', 'department_id' => 9],
            [ 'id' => 48 , 'name' => 'Labour Supervisor Asst.', 'department_id' => 9],
            [ 'id' => 49 , 'name' => 'Land Surveyor', 'department_id' => 9],
            [ 'id' => 50 , 'name' => 'Mason', 'department_id' => 9],
            [ 'id' => 51 , 'name' => 'Mechanic', 'department_id' => 9],
            [ 'id' => 52 , 'name' => 'MEP FOREMAN', 'department_id' => 9],
            [ 'id' => 53 , 'name' => 'Office Boy', 'department_id' => 9],
            [ 'id' => 54 , 'name' => 'ORDINARY LABOURER', 'department_id' => 9],
            [ 'id' => 55 , 'name' => 'Painter', 'department_id' => 9],
            [ 'id' => 56 , 'name' => 'Plumber', 'department_id' => 9],
            [ 'id' => 57 , 'name' => 'Plumber Charge-Hand', 'department_id' => 9],
            [ 'id' => 58 , 'name' => 'Safety Officer', 'department_id' => 9],
            [ 'id' => 59 , 'name' => 'Shovel Operator', 'department_id' => 9],
            [ 'id' => 60 , 'name' => 'Steel Fixer', 'department_id' => 9],
            [ 'id' => 61 , 'name' => 'Store Keeper', 'department_id' => 9],
            [ 'id' => 62 , 'name' => 'Store Keeper-MEP', 'department_id' => 9],
            [ 'id' => 63 , 'name' => 'Survey Helper', 'department_id' => 9],
            [ 'id' => 64 , 'name' => 'Time Keeper', 'department_id' => 9],
            [ 'id' => 65 , 'name' => 'WATCHMAN', 'department_id' => 9],
            [ 'id' => 66 , 'name' => 'Welder', 'department_id' => 9],
            [ 'id' => 67 , 'name' => 'Logistics Manager', 'department_id' => 10],
            [ 'id' => 68 , 'name' => 'MEP Site Engineer', 'department_id' => 11],
            [ 'id' => 69 , 'name' => 'Electrical Supervisor', 'department_id' => 11],
            [ 'id' => 70 , 'name' => 'MEP Estimator', 'department_id' => 11],
            [ 'id' => 71 , 'name' => 'MEP Draftsman', 'department_id' => 11],
            [ 'id' => 72 , 'name' => 'Electrical Engineer', 'department_id' => 11],
            [ 'id' => 73 , 'name' => 'Mechanical Engineer', 'department_id' => 11],
            [ 'id' => 74 , 'name' => 'MEP Coordinator', 'department_id' => 11],
            [ 'id' => 75 , 'name' => 'ERECTION FOREMAN', 'department_id' => 11],
            [ 'id' => 76 , 'name' => 'PROJECT MANAGER-MEP', 'department_id' => 11],
            [ 'id' => 77 , 'name' => 'MEP Procurement Officer', 'department_id' => 11],
            [ 'id' => 78 , 'name' => 'Document Controller', 'department_id' => 11],
            [ 'id' => 79 , 'name' => 'PLUMBING FOREMAN', 'department_id' => 11],
            [ 'id' => 114 , 'name' => 'MEP MANAGER', 'department_id' => 11],
            [ 'id' => 80 , 'name' => 'LIGHT VEHICLE DRIVER', 'department_id' => 12],
            [ 'id' => 81 , 'name' => 'BUS DRIVER', 'department_id' => 12],
            [ 'id' => 82 , 'name' => 'BOBCAT OPERATOR', 'department_id' => 12],
            [ 'id' => 83 , 'name' => 'Boom Loader Operator', 'department_id' => 12],
            [ 'id' => 84 , 'name' => 'BUS DRIVER', 'department_id' => 12],
            [ 'id' => 85 , 'name' => 'CHEF', 'department_id' => 12],
            [ 'id' => 86 , 'name' => 'CRANE OPERATOR', 'department_id' => 12],
            [ 'id' => 87 , 'name' => 'Driver', 'department_id' => 12],
            [ 'id' => 88 , 'name' => 'Grader Operator', 'department_id' => 12],
            [ 'id' => 89 , 'name' => 'HEAVY DUTY DRIVER', 'department_id' => 12],
            [ 'id' => 90 , 'name' => 'LIGHT VEHICLE DRIVER', 'department_id' => 12],
            [ 'id' => 91 , 'name' => 'Mechanic', 'department_id' => 12],
            [ 'id' => 92 , 'name' => 'PICKUP DRIVER', 'department_id' => 12],
            [ 'id' => 93 , 'name' => 'Shovel Operator', 'department_id' => 12],
            [ 'id' => 94 , 'name' => 'TRUCK DRIVER', 'department_id' => 12],
            [ 'id' => 95 , 'name' => 'TYREMAN', 'department_id' => 12],
            [ 'id' => 96 , 'name' => 'Safety Officer', 'department_id' => 13],
            [ 'id' => 97 , 'name' => 'Safety Manager', 'department_id' => 13],
            [ 'id' => 98 , 'name' => 'HSE Coordinator', 'department_id' => 13],
            [ 'id' => 99 , 'name' => 'Supervisor', 'department_id' => 14],
            [ 'id' => 100 , 'name' => 'Project Manager', 'department_id' => 14],
            [ 'id' => 101 , 'name' => 'Sr Foreman', 'department_id' => 14],
            [ 'id' => 102 , 'name' => 'Foreman', 'department_id' => 14],
            [ 'id' => 103 , 'name' => 'OFFICE GIRL', 'department_id' => 17],
            [ 'id' => 104 , 'name' => 'OFFICE Boy', 'department_id' => 17],
            [ 'id' => 105 , 'name' => 'Store Keeper', 'department_id' => 15],
            [ 'id' => 106 , 'name' => 'Land Surveyor', 'department_id' => 16],
            [ 'id' => 107 , 'name' => 'SR CIVIL SURVEYOR', 'department_id' => 16],
            [ 'id' => 108 , 'name' => 'SURVEY ENGINEER', 'department_id' => 16],
            [ 'id' => 109 , 'name' => 'ASST SURVEYOR', 'department_id' => 16],
            [ 'id' => 110 , 'name' => 'Quantity Surveyor', 'department_id' => 16],
            [ 'id' => 111 , 'name' => 'Others', 'department_id' => 17],

        ];
        foreach ($data as $key => $value) {
            \App\Models\Position::create([
                'id' => $value['id'],
                'name' => $value['name'],
                'department_id' => $value['department_id'],
            ]);
        }
    }
}
